routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

//Route::get('/home', 'HomeController@index')->name('home');

Route::group(['middleware' => 'auth'], function(){

    Route::get('/', 'HomeController@index');
    Route::get('/settings', 'SettingsController@index')->name('settings.index');
    Route::post('/settings', 'SettingsController@update')->name('settings.update');

    Route::resource('godown', 'GodownController');
    Route::resource('items', 'ItemController');
    Route::get('sales/items/html', 'SalesController@getHtml');
    Route::get('sales/items/validate/qty', 'SalesController@validateQty');

    Route::resource('sales', 'SalesController');
});

app/Item.php
<?php

namespace App;

use App\Tenant\TenantShopTrait;
use Illuminate\Database\Eloquent\Model;

class Item extends Model
{
    use TenantShopTrait;

    public function godown(){
        return $this->belongsTo(Godown::class);
    }

    public function getTotalAmountAttribute(){

        if($this->cartons == 0){
            return $this->qty_per_carton * $this->unit_price;
        }else{
            return $this->qty_per_carton * $this->unit_price * $this->cartons;
        }
    }

    public function getTitleAttribute()
    {
        return $this->serial_number . ' - ' . $this->name;
    }
}

app/Http/Controllers/ItemController.php
<?php

namespace App\Http\Controllers;

use App\Godown;
use App\Http\Requests;
use App\Item;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Facades\Validator;

class ItemController extends Controller {

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $search = $request->get('search');
        if ( $search )
        {
            $items = Item::where('serial_number', 'like', "%$search%")
                ->orWhere('name', 'like', "%$search%")
                ->orWhere('qty_per_carton', 'like', "%$search%")
                ->orWhere('unit_price', 'like', "%$search%")
                ->orWhere('cartons', 'like', "%$search%")
                ->orWhere('total_price', 'like', "%$search%")
                ->orderBy('created_at', 'DESC')
                ->paginate(50);
            $items->setPath('?search='.$search);
            return view('items.index', compact('items'));
        }
        else
        {
            $items = Item::paginate(50);

            return view('items.index', compact('items'));
        }
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $godowns = Godown::where('status', 1)->pluck('name', 'id');

        return view('items.create', compact('godowns'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        $rules = array(
            'serial_number'  => 'required|max:255|unique:items',
            'name'           => 'required',
            'qty_per_carton' => 'required|integer',
            'unit_price'     => 'required|numeric',
            'cartons'        => 'required|numeric',
            'godown_id'      => 'required'
        );
        $item = new Item();
        $validator = Validator::make($request->all(), $rules);
        if ( $validator->fails() )
        {
            return back()->with(['errors' => $validator->messages()])->withInput($request->all());
        }

        if ( $request->hasFile('photo') )
        {
            $fileName = Self::imageUpload($item, $request);

        }
        else
        {
            return redirect()->back()->with('message', 'Image is required');
        }

        if ( $request->cartons == 0 || $request->cartons == '')
        {
            $amount = $request->qty_per_carton * $request->unit_price;
            $total_qty = $request->qty_per_carton;
            $item->cartons = 0;
        }
        else
        {
            $amount = $request->qty_per_carton * $request->unit_price * $request->cartons;
            $total_qty = $request->qty_per_carton * $request->cartons;
            $item->cartons = $request->cartons;
        }

        $item->shop_id = Auth::user()->shop_id;
        $item->godown_id = $request->godown_id;
        $item->serial_number = $request->serial_number;
        $item->name = $request->name;
        $item->qty_per_carton = $request->qty_per_carton;
        $item->unit_price = $request->unit_price;
        $item->photo = $fileName;
        $item->total_price = $amount;
        $item->total_qty = $total_qty;
        $item->save();

        return redirect('items')->with('message', "Item has been created!");
    }

    public static function imageUpload($item, $request)
    {
        if ( $item->image != null )
        {
            if ( File::exists(public_path() . $item->photo) )
            {
                unlink(public_path() . $item->photo);
            }
        }

        $file = $request->file('photo');
        $destinationPath = public_path() . '/uploads/items';
        if ( !File::exists($destinationPath) )
        {
            mkdir($destinationPath, 0777, true);
        }
        $fileName = $file->getClientOriginalName();
        $fileName = time() . "_" . $fileName;
        $fileName = str_replace(" ", "_", $fileName);
        $file->move($destinationPath, $fileName);


        return '/uploads/items/' . $fileName;

    }






    /**
     * Display the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $item = Item::find($id);
        $godowns = Godown::where('status', 1)->pluck('name', 'id');

        return view('items.edit', compact('item', 'godowns'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $rules = array(
            'serial_number'  => 'required',
            'name'           => 'required',
            'qty_per_carton' => 'required|integer',
            'unit_price'     => 'required|numeric',
            'cartons'        => 'integer'

        );

        $item = Item::find($id);
        $validator = Validator::make($request->all(), $rules);
        if ( $validator->fails() )
        {
            return back()->with(['errors' => $validator->messages()])->withInput($request->all());
        }
        if ( $request->cartons == 0 || $request->cartons == '')
        {
            $amount = $request->qty_per_carton * $request->unit_price;
            $total_qty = $request->qty_per_carton;
            $item->cartons = 0;
        }
        else
        {
            $amount = $request->qty_per_carton * $request->unit_price * $request->cartons;
            $total_qty = $request->qty_per_carton * $request->cartons;
            $item->cartons = $request->cartons;

        }

        if ( $request->hasFile('photo') )
        {
            $fileName = $this->imageUpload($item, $request);

            $item->photo = $fileName;
        }

        $item->shop_id = Auth::user()->shop_id;
        $item->godown_id = $request->godown_id;
        $item->serial_number = $request->serial_number;
        $item->name = $request->name;
        $item->qty_per_carton = $request->qty_per_carton;
        $item->unit_price = $request->unit_price;
        $item->total_price = $amount;
        $item->total_qty = $total_qty;
        $item->save();

        return redirect('items')->with('message', "Item has been Updated!");
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $item = Item::find($id);
        if ( File::exists(public_path() . $item->photo) )
        {
            unlink(public_path() . $item->photo);
        }
        $item->delete();

        return redirect()->route('items.index')->with('message', 'Deleted Successfully!');
    }
}

resources/views/items/_form.blade.php
<div class="form-group{{ $errors->has('godown_id') ? ' has-error' : '' }}">
    <label class="col-md-4 control-label">Godowns</label>

    <div class="col-md-6">
        <div class="form-group">
            {!! Form::select('godown_id', $godowns, null, ['class' => 'form-control', 'id' => 'godown_id']) !!}
        </div>

        @if ($errors->has('godown_id'))
            <span class="help-block">
                                        <strong>{{ $errors->first('godown_id') }}</strong>
                                    </span>
        @endif
    </div>
</div>

<div class="form-group{{ $errors->has('serial_number') ? ' has-error' : '' }}">
    <label class="col-md-4 control-label">Sr #</label>

    <div class="col-md-6">
        <div class="form-group">
            {!! Form::text('serial_number', null, ['class' => 'form-control', 'id' => 'serial_number']) !!}
        </div>
        @if ($errors->has('name'))
            <span class="help-block">
                                        <strong>{{ $errors->first('serial_number') }}</strong>
                                    </span>
        @endif
    </div>
</div>

<div class="form-group{{ $errors->has('name') ? ' has-error' : '' }}">
    <label class="col-md-4 control-label">Name</label>

    <div class="col-md-6">
        <div class="form-group">
            {!! Form::text('name', null, ['class' => 'form-control', 'id' => 'name']) !!}
        </div>
        @if ($errors->has('name'))
            <span class="help-block">
                                        <strong>{{ $errors->first('name') }}</strong>
                                    </span>
        @endif
    </div>
</div>

<div class="form-group{{ $errors->has('qty_per_carton') ? ' has-error' : '' }}">
    <label class="col-md-4 control-label">Qty/Carton</label>

    <div class="col-md-6">
        <div class="form-group">
            {!! Form::text('qty_per_carton', null, ['class' => 'form-control', 'id' => 'qty_per_carton']) !!}
        </div>

        @if ($errors->has('qty_per_carton'))
            <span class="help-block">
                                        <strong>{{ $errors->first('qty_per_carton') }}</strong>
                                    </span>
        @endif
    </div>
</div>

<div class="form-group{{ $errors->has('unit_price') ? ' has-error' : '' }}">
    <label class="col-md-4 control-label">Unit Price</label>

    <div class="col-md-6">
        <div class="form-group">
            {!! Form::text('unit_price', null, ['class' => 'form-control', 'id' => 'unit_price']) !!}
        </div>
        @if ($errors->has('unit_price'))
            <span class="help-block">
                                        <strong>{{ $errors->first('unit_price') }}</strong>
                                    </span>
        @endif
    </div>
</div>
<div class="form-group{{ $errors->has('cartons') ? ' has-error' : '' }}">
    <label class="col-md-4 control-label"># of Cartons</label>

    <div class="col-md-6">
        <div class="form-group">
            {!! Form::text('cartons', null, ['class' => 'form-control', 'id' => 'cartons']) !!}
        </div>

        @if ($errors->has('cartons'))
            <span class="help-block">
                                        <strong>{{ $errors->first('cartons') }}</strong>
                                    </span>
        @endif
    </div>
</div>

<div class="form-group{{ $errors->has('photo') ? ' has-error' : '' }}">
    <label class="col-md-4 control-label">Upload Photo</label>

    <div class="col-md-6">
        <div class="form-group">
            <input type="file" class="form-control" name="photo">
        </div>

        @if ($errors->has('photo'))
            <span class="help-block">
                <strong>{{ $errors->first('photo') }}</strong>
            </span>
        @endif
    </div>
</div>

<div class="form-group">
    <div class="col-md-6 col-md-offset-4">
        <button type="submit" class="btn btn-primary">
            Save
        </button>
    </div>
</div>

resources/views/items/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="panel panel-default">
                    <div class="panel-heading">Add Item</div>
                    @if (count($errors) > 0)
                        <div class="alert alert-danger">
                            <ul>
                                @foreach ($errors->all() as $error)
                                    <li>{{ $error }}</li>
                                @endforeach
                            </ul>
                        </div>
                    @endif

                    @if(Session::has('message'))

        <div class="alert alert-info">
            <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
            <strong>Info!</strong>  {{Session::get('message')}}
        </div>
    @endif
                    <div class="panel-body">
                        {!!Form::open(array('route' => ['items.store']  , 'method' => 'POST', 'files' => 'true'))!!}

                            @include('items._form')

                        {!!Form::close()!!}
                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection

resources/views/items/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="panel panel-default">
                    <div class="panel-heading">Edit Item</div>
                    @if(Session::has('message'))

                        <div class="alert alert-info">
                            <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                            <strong>Info!</strong>  {{Session::get('message')}}
                        </div>
                    @endif
                    @if (count($errors) > 0)
                        <div class="alert alert-danger">
                            <ul>
                                @foreach ($errors->all() as $error)
                                    <li>{{ $error }}</li>
                                @endforeach
                            </ul>
                        </div>
                    @endif
                    <div class="panel-body">
                        {!!Form::model($item, array('route' => ['items.update' , $item->id]  , 'method' => 'put', 'files' => 'true'))!!}

                        @include('items._form')

                        {!!Form::close()!!}
                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection

resources/views/items/index.blade.php
@extends('layouts.app')

@section('content')
    @if(Session::has('message'))

        <div class="alert alert-info">
            <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
            <strong>Info!</strong>  {{Session::get('message')}}
        </div>
    @endif

    <div class="wrapper wrapper-content animated fadeInRight">

        <div class="row">
            <div class="col-lg-12">
                <div class="ibox float-e-margins">
                    <div class="ibox-title">
                        <div class="col-md-6">
                            <h5>Manage Items
                            </h5>
                        </div>
                        <div class="col-md-6 pull-right">
                            <a style="margin-left: 5px;" href="{!! route('items.create') !!}" class="btn btn-primary btn-sm pull-right"> <i class="fa fa-plus"></i> Add Item </a>

                            <form method="get" action="/items" class="pull-right mail-search">
                                <div class="input-group">
                                    <input type="text" class="form-control input-sm" name="search" id="search" value="" placeholder="Search" required>
                                    {{--<input type="hidden" name="email_type" id="email_type">--}}
                                    <div class="input-group-btn">
                                        <button type="submit" class="btn btn-sm btn-primary">
                                            Search
                                        </button>
                                    </div>
                                </div>
                            </form>
                        </div>
                        <div class="clearfix"></div>
                    </div>

                    <br>
                    <div class="ibox-content">

                        <table class="footable table table-stripped toggle-arrow-tiny" data-page-size="8">
                            <thead>
                            <tr>


                                <th>Photo</th>
                                <th>Code</th>
                                <th>Name</th>
                                <th>Godown</th>
                                <th>Qty/Carton</th>
                                <th># of Carton(s) Left</th>
                                <th>Total Qty Left</th>
                                <th>Unit Price</th>
                                <th>Total Amount</th>
                                <th>Action</th>
                            </tr>
                            </thead>
                            <tbody>

                            <?php $total = 0 ?>
                            @forelse($items as $item)
                                <tr>
                                    <td><img src="{{$item->photo}}" alt="item" style="width:130px;height:100px;"></td>
                                    <td>{{$item->serial_number}}</td>
                                    <td>{{$item->name}}</td>
                                    <td>{{ $item->godown->name }}</td>
                                    <td>{{$item->qty_per_carton}}</td>
                                    <td>{{ number_format($item->cartons, 2)}}</td>
                                    <td>{{ $item->total_qty }}</td>
                                    <td>{{$item->unit_price}}</td>
                                    <td>{{number_format($item->total_amount, 2)}}</td>
                                    <td>
                                        <a href="/items/{{$item->id}}/edit" class="btn btn-success btn-sm"><i class="fa fa-pencil-square-o" aria-hidden="true"></i> Edit</a>
                                        {{Form::open(array('action' => array('ItemController@destroy', $item->id) , 'method'=>'DELETE', 'style' => 'display:inline'))}}
                                        <button  type="submit" class="btn btn-danger btn-sm">Delete</button>
                                        {{Form::close()}}
                                    </td>

                                </tr>
                                    <?php $total += $item->total_price ?>

                            @empty
                                <tr>
                                    <td colspan="10">No purchase items found!</td>
                                </tr>

                                @endforelse

                            </tbody>
                            <tfoot>
                            <tr>
                                <td colspan="5">
                                    <ul class="pagination pull-right"></ul>
                                </td>
                            </tr>
                            </tfoot>
                        </table>
                        <div class="pull-right"><b>Total Amount:</b> {!! $total !!}.00</div>
                        {{ $items->links() }}

                    </div>
                </div>
            </div>
        </div>

    </div>
@endsection